# Generated by Django 4.2.3 on 2023-07-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=10)),
                ('pic', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
